blog/urls.py
from django.urls import path

from . import views
from .views import PostsView, ShowPost, CreatePost, CategoryView


app_name = 'blog'
urlpatterns = [
    path('', PostsView.as_view(), name='index'),
    path('create', CreatePost.as_view(), name='create_post'),
    path('post/<slug:post_slug>', ShowPost.as_view(), name='show_post'),
    path('cat/<slug:cat_slug>', CategoryView.as_view(), name='show_cat')
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('blog/', include('blog.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path

from . import views


app_name = 'website'
urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about),
    path('create', views.create),
    path('delete/<int:id>', views.delete),
    path('buy/<int:id>', views.buy),
]

blog/models.py
from django.urls import reverse
from django.utils.text import slugify
from unidecode import unidecode

from django.db import models


# Create your models here.
class PostModel(models.Model):
    author = models.CharField('Автор статьи', max_length=30)
    title = models.CharField('Название статьи', max_length=50)
    slug = models.SlugField('URL', max_length=60, unique=True, db_index=True, null=True, blank=True)
    text = models.TextField('Текст статьи')
    image = models.ImageField('Картинка к посту', upload_to='img')  # pillow
    publish_date = models.DateTimeField('Время публикации', auto_now=True)
    is_published = models.BooleanField('Пост опубликован?', default=True)
    category = models.ForeignKey('Category', on_delete=models.PROTECT, verbose_name='Категория')

    def get_absolute_url(self):
        return reverse('blog:show_post', kwargs={'post_slug': self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            string = str(self.title)
            self.slug = slugify(unidecode(string))
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.title


# статья -> statia
class Category(models.Model):
    name = models.CharField('Категория', max_length=30, unique=True)
    slug = models.SlugField('URL', max_length=30, unique=True, db_index=True)

    def get_absolute_url(self):
        return reverse('blog:show_cat', kwargs={'cat_slug': self.slug})

    def __str__(self):
        return self.name

contacts/models.py
from django.db import models

# Create your models here.

website/models.py
from django.db import models


# Create your models here.
class Product(models.Model):
    name = models.CharField('Название продукта', max_length=30)
    description = models.TextField('Описание продукта')
    price = models.IntegerField('Цена продукта')

    def __str__(self):
        return self.name

blog/forms.py
from django.forms import ModelForm, TextInput, Textarea, SlugField

from .models import PostModel


# Class Based Forms (CBF)
class PostForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['author'].label = 'Автор статьи'
        self.fields['title'].label = 'Название статьи'
        self.fields['text'].label = 'Текст статьи'
        self.fields['slug'].label = 'URL статьи'
        self.label_suffix = ""
        self.fields['category'].empty_label = 'Категория не выбрана'

    class Meta:
        model = PostModel
        fields = ['author', 'title', 'slug', 'text', 'image', 'category']
        widgets = {
            'author': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите автора статьи',
                'id': 'author-input'
            }),
            'title': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите название статьи',
                'id': 'title-input'
            }),
            'text': Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Введите текст статьи',
                'id': 'text-input'
            }),
            'slug': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите URL статьи (необязательно)',
                'id': 'slug-input'
            })
        }

    def clean_title(self):
        title = self.cleaned_data['title']
        if len(title) > 50:
            self.add_error('title', 'Больше 50 символов!')
        if '!!' in title:
            self.add_error('title', 'Очень много восклицательных знаков!!!')
        return title

blog/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, CreateView
from django.urls import reverse_lazy

from .models import PostModel
from .forms import PostForm


class PostsView(ListView):
    model = PostModel
    template_name = 'blog/index.html'
    context_object_name = 'posts'
    # extra_context = {'title': 'Главная страница'}

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Главная страница'
        return context

    def get_queryset(self):
        return PostModel.objects.filter(is_published=True)


class CategoryView(ListView):
    model = PostModel
    template_name = 'blog/index.html'
    context_object_name = 'posts'
    # extra_context = {'title': 'Главная страница'}
    allow_empty = False

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Главная страница'
        return context

    def get_queryset(self):
        return PostModel.objects.filter(category__slug=self.kwargs['cat_slug'])


# Slug
class ShowPost(DetailView):
    model = PostModel
    template_name = 'blog/show_post.html'
    slug_url_kwarg = 'post_slug'
    context_object_name = 'post'


class CreatePost(CreateView):
    form_class = PostForm
    template_name = 'blog/create.html'

contacts/views.py
from django.shortcuts import render

# Create your views here.

website/views.py
from datetime import datetime

from django.shortcuts import render, redirect
from cloudipsp import Api, Checkout

from .models import Product


# Create your views here.
def index(request):
    products = Product.objects.all()
    context = {
        'products': products,
        'collection': 'папа мама я - огромная семья'.split(),
        'string': 'Можно найти всё на www.ya.ru https://www.ya.ru http://ya.ru ya.ru',
        'dct': {'one': 1, 'two': 2, 'three': 3},
        'number': 212,
        'date': datetime.now(),
        'html': '<script>alert(1)</script>'
    }
    return render(request, 'website/index.html', context)


def about(request):
    return render(request, 'website/about.html')


def create(request):
    if request.method == 'POST':
        product = Product(
            name=request.POST.get('name'),
            description=request.POST.get('description'),
            price=request.POST.get('price')
        )
        product.save()
    return render(request, 'website/create.html')


def delete(request, id):
    Product.objects.filter(id=id).delete()
    return redirect('website:index')


def buy(request, id):
    products = Product.objects.get(id=id)

    api = Api(merchant_id=1396424, secret_key='test')
    checkout = Checkout(api=api)
    data = {
        "currency": "RUB",
        "amount": str(products.price) + '00'
    }
    url = checkout.url(data).get('checkout_url')
    return redirect(url)

blog/templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}{% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

<header>
    <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4 class="text-white">О нас</h4>
                    <p class="text-muted">Блог обо мне и о мире вокруг.</p>
                </div>
                <div class="col-sm-4 offset-md-1 py-4">
                    <h4 class="text-white">Навигация</h4>
                    <ul class="list-unstyled">
                        <li><a href="{% url 'blog:index' %}" class="text-white">Главная</a></li>
                        <li><a href="{% url 'blog:create_post' %}" class="text-white">Создать пост</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container">
            <a href="{% url 'blog:index' %}" class="navbar-brand d-flex align-items-center">
                <strong>Главная</strong>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>

<div class="container mt-5">
    {% block body %}{% endblock %}
</div>

<footer class="text-muted py-5">
    <div class="container">
        <p class="float-end mb-1">
            <a href="#">Back to top</a>
        </p>
        <p class="mb-1">Album example is © Bootstrap, but please download and customize it for yourself!</p>
        <p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a
                href="/docs/5.1/getting-started/introduction/">getting started guide</a>.</p>
    </div>
</footer>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>

</body>
</html>

blog/templates/blog/create.html
{% extends 'blog/base.html' %}

{% block body %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for el in form %}
         <div class="mb-3">
            <div class="form-floating">
                {% if el.label != 'Картинка к посту' and el.label != 'Категория' %}
                    {{ el }}
                    {{ el.label_tag }}
                {% else %}
                    {{ el.label }}
                    {{ el }}
                {% endif %}
            </div>
            {% if el.errors %}
                <ol>
                {% for error in el.errors %}
                    <li><strong class="text-danger">{{ error }}</strong></li>
                {% endfor %}
                </ol>
             {% endif %}
         </div>
    {% endfor %}
    <button type="submit" class="btn btn-primary">Опубликовать</button>
</form>
<h3>{{ error }}</h3>
{% endblock %}c4

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block title %}
<title>{{ title }}</title>
{% endblock %}

{% block body %}
<main>
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for post in posts %}
        <div class="col">
            <div class="card h-100">
                <img src="{{ post.image.url }}" class="card-img-top" width="100">
                <div class="card-body">
                    <h5 class="card-title">{{post.author}}. {{ post.title }}</h5>
                    <p class="card-text">{{ post.text|truncatewords:"15" }}</p>
                </div>
                <div class="d-flex card-footer justify-content-between">
                    <small class="text-muted">{{ post.publish_date|timesince }} назад</small>
                    <small class="text-muted"><a class="text-secondary" href="{% url 'blog:show_post' post.slug %}">Читать пост -></a></small>
                </div>
            </div>
        </div>
        {% empty %}
        <h1>Нет ни одного поста!</h1>
        {% endfor %}
    </div>
</main>
{% endblock %}

blog/templates/blog/show_post.html
{% extends 'blog/base.html' %}

{% block title %}
<title>{{ title }}</title>
{% endblock %}

{% block body %}
    <img src="{{ post.image.url }}" class="card-img-top">
    <p>{{ post.title }}</p>
    <p>{{ post.author }}</p>
    <p>{{ post.publish_date }}</p>
    <p>{{ post.text }}</p>
{% endblock %}

website/templates/website/about.html
{% extends 'website/base.html' %}

{% block title %}
<title>Главная</title>
{% endblock %}

{% block about %}
<div class="pricing-header p-3 pb-md-4 mx-auto text-center">
    <h1 class="display-4 fw-normal">Pricing</h1>
    <p class="fs-5 text-muted">Quickly build an effective pricing table for your potential customers with this
        Bootstrap example. It’s built with default Bootstrap components and utilities with little
        customization.</p>
</div>
{% endblock %}

website/templates/website/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}{% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
    <symbol id="check" viewBox="0 0 16 16">
        <title>Check</title>
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"></path>
    </symbol>
</svg>

<div class="container py-3">
    <header>
        <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
            <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
                <img src="{% static 'website/img/apple_logo.png' %}" width="40">
                <span class="fs-4">Магазин ShagProducts</span>
            </a>

            <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
                <a class="me-3 py-2 text-dark text-decoration-none" href="/">Главная</a>
                <a class="me-3 py-2 text-dark text-decoration-none" href="/about">О нас</a>
                <a class="me-3 py-2 text-dark text-decoration-none" href="/create">Добавить товар</a>
            </nav>
        </div>

        {% block about %}{% endblock %}
    </header>

    {% block body %}{% endblock %}

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                <img src="{% static 'website/img/apple_logo.png' %}" width="24">
                <small class="d-block mb-3 text-muted">© 2017–2021</small>
            </div>
            <div class="col-6 col-md">
                <h5>Features</h5>
                <ul class="list-unstyled text-small">
                    <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Cool stuff</a></li>
                    <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Random feature</a></li>
                    <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Team feature</a></li>
                    <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Stuff for developers</a>
                    </li>
                    <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Another one</a></li>
                    <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Last time</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Resources</h5>
                <ul class="list-unstyled text-small">
                    <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Resource</a></li>
                    <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Resource name</a></li>
                    <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Another resource</a></li>
                    <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Final resource</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>About</h5>
                <ul class="list-unstyled text-small">
                    <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Team</a></li>
                    <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Locations</a></li>
                    <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Privacy</a></li>
                    <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Terms</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'website/js/js.js' %}"></script>
</body>
</html>

website/templates/website/create.html
{% extends 'website/base.html' %}

{% block title %}
    <title>Добавление товара</title>
{% endblock %}

{% block body %}
    <form method="POST">
        {% csrf_token %}
    <div class="form-floating mb-3">
        <input name="name" type="text" class="form-control" id="floatingInput" placeholder="Название товара" autocomplete="off">
        <label for="floatingInput">Название товара</label>
    </div>
    <div class="form-floating mb-3">
        <input name="description" type="text" class="form-control" id="floatingPassword"
               placeholder="Описание товара">
        <label for="floatingPassword">Описание товара</label>
    </div>
    <div class="form-floating mb-3">
        <input name="price" type="number" class="form-control" id="floatingPassword" placeholder="Цена">
        <label for="floatingPassword">Цена</label>
    </div>
    <button type="submit" class="btn btn-primary">Создать товар</button>
</form>
{% if error %}
    <h1>{{ error }}</h1>
{% endif %}
{% endblock %}

website/templates/website/index.html
{% extends 'website/base.html' %}

{% block title %}
<title>Главная</title>
{% endblock %}

{% block body %}
<main>
    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
        {% for product in products %}
        <div class="col">
            <div class="card mb-4 rounded-3 shadow-sm">
                <div class="card-header py-3">
                    <div class="d-flex justify-content-between">
                        <div></div>
                        <h4 class="my-0 fw-normal" id="header-{{ product.id }}">{{ product.name }}</h4>
<!--                        <a href="/delete/{{ product.id }}"><button type="button" class="btn-close" id="closeButton" aria-label="Close"></button></a>-->
                        <button type="button" class="btn-close button-card" id="closeButton" value="{{ product.id }}" aria-label="Close" data-bs-toggle="modal" data-bs-target="#exampleModal"></button>
                    </div>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">{{ product.price }}<small
                            class="text-muted fw-light">руб.</small>
                    </h1>
                    <ul class="list-unstyled mt-3 mb-4">
                        <li>{{ product.description }}</li>
                    </ul>
                    <a href="/buy/{{ product.id }}">
                        <button type="button" class="w-100 btn btn-lg btn-outline-primary">Купить!</button>
                    </a>
                </div>
            </div>
        </div>
        {% empty %}
            <p>Данных нет!</p>
        {% endfor %}
    </div>

    {% for el in collection %}
        {% if forloop.last %}
            <h1>{{ el }} {{ forloop.revcounter0 }}</h1>
        {% else %}
            <p>{{ el }} {{ forloop.revcounter0 }}</p>
        {% endif %}
        <p>Случайный элемент {{ collection|random }}</p>
    {% endfor %}

    <p>{{ string1|default:"Новая надпись о том, что строки нет" }}</p>

    {% if collection|length_is:"6" %}
        <p>Длина списка: {{ collection|length }}</p>
    {% endif %}

    <p>{{ collection|join:" // " }}</p>

    {# <p> {{ string|add:collection|join:" // " }} </p> #}

    {{ string|urlizetrunc:"2" }}

    <p>{{ string|wordwrap:"7" }}</p>

    {% if number|divisibleby:"3" %}
        <p>Делится</p>
    {% else %}
        <p>Не делится</p>
    {% endif %}

    {# {{ date|date:"SHORT_DATE_FORMAT" }} #}

    {% now "d m Y H:m:s" %}

    {% include 'website/modal-delete.html' %}

    {% for i in ''|ljust:"10" %}
        <p style="color: {% cycle 'red' 'green' 'blue' %}">{{ forloop.counter }}</p>
    {% endfor %}

    {% if dct %}
        {{ dct }}
    {% elif number %}
        {{ number }}
    {% elif date %}
        {{ date }}
    {% else %}
        Нет ничего!!!
    {% endif %}

    {% firstof dct number date "Нет ничего!!!" %}

    {% lorem 2 p random %}

    {# <p> {{ string|add:collection|join:" // " }} </p> #}
    {% with col=collection|join:" // " %}
        <p> {{ string|add:col }} </p>
    {% endwith %}

    {% with col=collection|join:" // " col2=2 %}
        <p> {{ string|add:col }} {{ col2 }}</p>
    {% endwith %}

    {% autoescape on %}
        {{ html }}
    {% endautoescape %}

    <h2 class="display-6 text-center mb-4">Compare plans</h2>

    <div class="table-responsive">
        <table class="table text-center">
            <thead>
            <tr>
                <th style="width: 34%;"></th>
                <th style="width: 22%;">Free</th>
                <th style="width: 22%;">Pro</th>
                <th style="width: 22%;">Enterprise</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <th scope="row" class="text-start">Public</th>
                <td>
                    <svg class="bi" width="24" height="24">
                        <use xlink:href="#check"></use>
                    </svg>
                </td>
                <td>
                    <svg class="bi" width="24" height="24">
                        <use xlink:href="#check"></use>
                    </svg>
                </td>
                <td>
                    <svg class="bi" width="24" height="24">
                        <use xlink:href="#check"></use>
                    </svg>
                </td>
            </tr>
            <tr>
                <th scope="row" class="text-start">Private</th>
                <td></td>
                <td>
                    <svg class="bi" width="24" height="24">
                        <use xlink:href="#check"></use>
                    </svg>
                </td>
                <td>
                    <svg class="bi" width="24" height="24">
                        <use xlink:href="#check"></use>
                    </svg>
                </td>
            </tr>
            </tbody>

            <tbody>
            <tr>
                <th scope="row" class="text-start">Permissions</th>
                <td>
                    <svg class="bi" width="24" height="24">
                        <use xlink:href="#check"></use>
                    </svg>
                </td>
                <td>
                    <svg class="bi" width="24" height="24">
                        <use xlink:href="#check"></use>
                    </svg>
                </td>
                <td>
                    <svg class="bi" width="24" height="24">
                        <use xlink:href="#check"></use>
                    </svg>
                </td>
            </tr>
            <tr>
                <th scope="row" class="text-start">Sharing</th>
                <td></td>
                <td>
                    <svg class="bi" width="24" height="24">
                        <use xlink:href="#check"></use>
                    </svg>
                </td>
                <td>
                    <svg class="bi" width="24" height="24">
                        <use xlink:href="#check"></use>
                    </svg>
                </td>
            </tr>
            <tr>
                <th scope="row" class="text-start">Unlimited members</th>
                <td></td>
                <td>
                    <svg class="bi" width="24" height="24">
                        <use xlink:href="#check"></use>
                    </svg>
                </td>
                <td>
                    <svg class="bi" width="24" height="24">
                        <use xlink:href="#check"></use>
                    </svg>
                </td>
            </tr>
            <tr>
                <th scope="row" class="text-start">Extra security</th>
                <td></td>
                <td></td>
                <td>
                    <svg class="bi" width="24" height="24">
                        <use xlink:href="#check"></use>
                    </svg>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</main>
{% endblock %}

website/templates/website/modal-delete.html
<!-- Modal Delete Object -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Этот продукт удалится на всегда!
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Нет</button>
        <a href="#" id="deleteLink"><button type="button" class="btn btn-danger">Да</button></a>
      </div>
    </div>
  </div>
</div>